### ISSUE TITLE
Review for Tarik's Portfolio

### ISSUE THREAD

**Issue by michael-duke** [tarikbouari/My-Portfolio-Website#10]
## Salut Tarik

I think your website looks nice. Here are some things to make it look more similar with the Figma design:

- NavLinks are well placed I would recommend to give them a `font-weight` so they can cacth a lil attention, I think 500 should do it.
- Your header has a smaller height than the design, make it a lil tall so we can see the background image.
- I like the social media icons, I suggest you use svg so they can look more nicer, so if you can replace them that's great.
- For the projects make sure the fonts are the same as the design they look a lil big to me the, but check it.
- I saw that for IPad the ul.specific wraps, you can use `white-space: nowrap` to take care of that.
- In the about  section, you can also use the `font-weight` and `color` used in the design for the Language, Framwork..texts. I also suggest you use `border-bottom` instead of `hr` for the separators.
- Finally the text under the languages in the `ul class="lang-child"` seem to small for me, and use the same width for all of them.
- You can also add in the css the `scroll-behavior: smooth` so when you click the anchors it happens smoothly
**Be sure to text me on slack @tarikbouari , we schedule a call this weekif you need any more suggestions.**

**Comment by tarikbouari** [comment]
Thank you for your review @michael-duke I will work on your suggestions and make the changes.
