### ISSUE TITLE
Peer to peer code review

### ISSUE THREAD

**Issue by shyusu4** [tarikbouari/My-Portfolio-Website#13]
Hi @tarikbouari 👋 , your portfolio looks great 👍 Here are some suggestions on how you can improve it:

- It would be good to add correct image alignment in the desktop version of my works card section.
- Kindly add a responsive image size for the mobile version.
- You can change the images and icons to .svg to have better quality.

**[OPTIONAL]**
-  The design would match the Figma design more with a navbar shadow.

**Comment by tarikbouari** [comment]
Thanks for your review, I will implement the suggested changes.
