### ISSUE TITLE
Morning-session-discussion

### ISSUE THREAD

**Issue by mahdimahdawi** [tarikbouari/My-Portfolio-Website#6]
You can comment your suggestion Here.

**Comment by tarikbouari** [comment]
What did you think about my project dear teammate?

**Comment by ZikaZaki** [comment]
the **Let's connect** must be clickable .

**Comment by ZikaZaki** [comment]
The `padding` and `gaps` spaces are not equal in the projects section.

**Comment by mahdimahdawi** [comment]
According to figma the Back end Dev texts are normal text yours in bold change it to normal font.

**Comment by mahdimahdawi** [comment]
In contact form page background shapes are not in the right position according to figma, please kindly fix that.

**Comment by Recillah-Khamala** [comment]
Good job on this project, Tarik. Kindly ensure that all your buttons are working as required.
