### ISSUE TITLE
Website deploy. 

### ISSUE THREAD

**Issue by tarikbouari** [tarikbouari/My-Portfolio-Website#9]
Here is the link for the preview of my project 

[click here](https://tarikbouari.github.io/My-Portfolio-Website/)

**Comment by prolajumokeoni** [comment]
Hi @tarikbouari, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
- Good design 💯 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by tarikbouari** [comment]
Thank you for your time and review
